# Generated by Django 4.1.5 on 2023-02-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositoryfiles",
            name="proponents",
            field=models.ManyToManyField(
                related_name="repository_proponents", to="Users.proponent"
            ),
        ),
    ]
