# Generated by Django 4.1.5 on 2023-02-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploaddocuments",
            name="student_proponents",
        ),
        migrations.AddField(
            model_name="uploaddocuments",
            name="student_proponents",
            field=models.ManyToManyField(
                related_name="student_proponents", to="Users.studentusers"
            ),
        ),
    ]
