# Generated by Django 4.1.5 on 2023-03-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_documentsproponents_alter_documents_docs_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="profile_picture",
            field=models.ImageField(upload_to="profile_pictures/"),
        ),
        migrations.AlterField(
            model_name="panel",
            name="profile_picture",
            field=models.ImageField(upload_to="profile_pictures/"),
        ),
        migrations.AlterField(
            model_name="similaritythreshold",
            name="threshold",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(upload_to="profile_pictures/"),
        ),
    ]
