# Generated by Django 4.1.5 on 2023-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_repositoryfiles_text_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "profile_pictures/",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="documentcomparison",
            name="doc1_pdf_file",
            field=models.FileField(
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "ComparisonDocs/",
                )
            ),
        ),
        migrations.AlterField(
            model_name="documentcomparison",
            name="doc2_pdf_file",
            field=models.FileField(
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "ComparisonDocs/",
                )
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:\\Users\\Admin\\Desktop\\thesis-project\\media/profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="repositoryfiles",
            name="pdf_file",
            field=models.FileField(
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "RepositoryFiles/",
                )
            ),
        ),
        migrations.AlterField(
            model_name="repositoryfiles",
            name="text_file",
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "profile_pictures/",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="uploaddocuments",
            name="student_pdf_file",
            field=models.FileField(
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "DefFiles/",
                )
            ),
        ),
    ]
