# Generated by Django 4.1.5 on 2023-01-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0010_alter_similaritythreshold_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "profile_pictures/",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "profile_pictures/",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=(
                    "C:\\Users\\Admin\\Desktop\\thesis-project\\media/",
                    "profile_pictures/",
                ),
            ),
        ),
    ]
