# Generated by Django 4.1.5 on 2023-02-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0011_alter_admin_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryfiles",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploaddocuments",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="C:\\Users\\Admin\\Desktop\\thesis-project\\media/profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="C:\\Users\\Admin\\Desktop\\thesis-project\\media/profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="C:\\Users\\Admin\\Desktop\\thesis-project\\media/profile_pictures/",
            ),
        ),
    ]
