# Generated by Django 4.1.5 on 2023-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0013_uploaddocuments_threshold_result_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documents",
            old_name="similarity",
            new_name="content_similarity",
        ),
        migrations.AddField(
            model_name="documents",
            name="title_similarity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="repositoryfiles",
            name="description",
            field=models.CharField(default="repository", max_length=255),
        ),
        migrations.AlterField(
            model_name="admin",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="uploaddocuments",
            name="document_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
