# Generated by Django 4.1.5 on 2023-02-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0014_rename_similarity_documents_content_similarity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="panelusers",
            name="group",
            field=models.CharField(default="Panel", max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.CharField(default="Student", max_length=50),
        ),
    ]
